# -*- coding: utf-8 -*-
"""Correlacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PScss7ojWBWtk8xnQfZ0WYpKQ25OXtsG
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col , expr , mean, corr

spark=SparkSession.builder.appName("Correlacion").getOrCreate()

spark

"""
Contexto
Determinamos si existe una relacion entre la cantidad de horas que los estudiantes estudian y el puntaje que obtiene en un examen, mostraremos un total de 10 alumnos.
"""

csv_file_path = "/content/Correlacion.csv"
project_correlacion = spark.read.csv(csv_file_path, header=True, inferSchema=True, sep=";")

project_correlacion.show()

correlacion=project_correlacion.select(corr(col("Horas de estudio"),col("Puntajes de examen")).alias("correlacion")).collect()[0]["correlacion"]

print("La correlacion es: " , correlacion)