# -*- coding: utf-8 -*-
"""Media.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T160M-77LHVtdFaS-Fvk7NgI6Vh6eBLB
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col , expr , mean, corr

spark=SparkSession.builder.appName("Media").getOrCreate()

spark

"""
Contexto
En una tienda se requiere calcular el promedio de ventas que realizaron los empleados durante el mes.
"""

csv_file_path = "/content/Media.csv"
project_media = spark.read.csv(csv_file_path, header=True, inferSchema=True, sep=";")

project_media.show()

project_media.select(mean(col("Ventas")).alias("Media")).show()

project_media.select(mean(col("Ventas")).alias("Media")).collect()[0]["Media"]