# -*- coding: utf-8 -*-
"""Mediana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2NhyRrwcUH5kvXrLtd72p8gDPOKaAiy
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col , expr , mean, corr

spark=SparkSession.builder.appName("Mediana").getOrCreate()

spark

"""
Contexto
Proporcionaremos de una manera mas precisa los ingresos tipico de las personas en tal ciudad.
"""

csv_file_path = "/content/Mediana.csv"
project_mediana = spark.read.csv(csv_file_path, header=True, inferSchema=True, sep=";")

project_mediana.show()

var_mediana=project_mediana.approxQuantile("Ingresos",[0.5],0.0)

print("La mediana es" , var_mediana)