# -*- coding: utf-8 -*-
"""Moda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_9XW_HD3mXG2o4OWjyoqmqUXOLt8e1KF
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col , expr , mean, corr

spark=SparkSession.builder.appName("Moda").getOrCreate()

spark

"""
Contexto
Una tienda de ropa quiere saber cual es la talla de ropa mas popular entre sus clientes, de esta manera optimizar el inventario
"""

csv_file_path = "/content/Moda.csv"
project_moda = spark.read.csv(csv_file_path, header=True, inferSchema=True, sep=";")

var_moda=project_moda.groupBy("Tallas").count().orderBy(col("count").desc()).first()

print("La talla mas popular es:", var_moda["Tallas"])